// Edit this file to update portfolio content. Keep confidential company data out.
window.PORTFOLIO_CONTENT = {
  name: "Jessica Kaluiji", title: "Data Scientist | Data Analyst | Business Intelligence",
  phrase: "Curious. Practical. Purpose-led.", location: "Kalumbila, North-Western Province, Zambia",
  email: "kaluijijessica@gmail.com", phone: "+260 974 268 368", showPhone: true,
  cv: "assets/Jessica-Kaluiji-CV.pdf",
  social: { linkedin: "https://www.linkedin.com/in/jessica-kaluiji-97750a19b/", github: "https://github.com/kaluijijessica" },
  capabilities: ["Analyse", "Engineer", "Build", "Communicate", "Improve"],
  projects: [
    { title: "Excess Hour and Recovery Monitoring", category: "Safety Analytics | Data Engineering | Business Intelligence", summary: "A monitoring solution that transforms raw clocking events into reliable work and recovery measures, giving managers a consistent way to identify extended work periods, short recovery intervals and historical patterns.", problem: "Manual review made it difficult to monitor patterns consistently and respond promptly.", contribution: ["Built SQL logic to pair clock-in and clock-out events", "Classified shifts and calculated work and recovery periods", "Investigated exceptions and data-quality issues", "Developed current and historical Power BI monitoring", "Delivered automated daily alerts", "Tested and refined reporting logic with stakeholders"], approach: "Validated event data first, translated agreed rules into reusable SQL logic, and layered reporting and alerts onto a governed dataset.", outcome: "Moved the process from manual review to consistent recurring monitoring with proactive alerts and historical visibility.", tools: ["SQL Server", "T-SQL", "Power BI", "DAX", "Power Automate", "Data validation"], visual: "shift" },
    { title: "Compliance and Competency Reporting", category: "Workforce Analytics | Data Integration | Automated Alerts", summary: "A reporting solution that combines role requirements, learning records and organisational information to show compliance, competency, upcoming expiry and gaps by department.", problem: "Fragmented records and inconsistent definitions limited early visibility of upcoming requirements.", contribution: ["Combined role, learning and reporting information", "Resolved duplicate roles and missing organisational fields", "Defined separate rules for compliance and practical competency", "Created department-level views", "Built proactive expiry alerts", "Validated definitions with stakeholders"], approach: "Integrated several controlled datasets, separated distinct business concepts, and built validation checks before publishing department views.", outcome: "Teams gained earlier visibility of upcoming requirements and a more proactive notification process.", tools: ["SQL Server", "Power BI", "DAX", "Power Query", "Data validation", "Workflow automation"], visual: "compliance" },
    { title: "Unified Tasks and Approvals Dashboard", category: "ETL | Workflow Intelligence | Governed Reporting", summary: "A consolidated view of tasks and approvals from several workflow and learning processes, helping owners review outstanding work across systems in one place.", problem: "Task owners had to review fragmented queues with inconsistent statuses and ownership data.", contribution: ["Prepared and combined data from multiple sources", "Standardised inconsistent task statuses", "Created a governed SQL dataset", "Built role-based Power BI access", "Set up repeatable updates", "Validated ownership, status and duplicate records"], approach: "Mapped source fields into a shared task model, created repeatable transformations and applied access rules at the reporting layer.", outcome: "Reduced fragmented review across separate systems and created a clearer view of outstanding work.", tools: ["SQL Server", "ETL", "Power BI", "Row-level security", "Data modelling", "Data-quality checks"], visual: "workflow" },
    { title: "Process Water Balance Application", category: "Software Development | Process Data | Agile Delivery", summary: "A .NET and SQL Server application for controlled monthly water-balance entries, designed with Process and Dewatering stakeholders and prepared for consolidated reporting.", problem: "Monthly information depended heavily on spreadsheets and needed a more controlled collection process.", contribution: ["Gathered cross-functional requirements", "Developed the application with C# and .NET", "Created controlled statuses and input validation", "Mapped manual and reconciled information", "Designed the reporting data flow", "Revised the application through stakeholder testing"], approach: "Used iterative delivery to turn operational requirements into validated inputs, controlled states and a maintainable reporting path.", outcome: "Produced a working application and a more controlled structure for monthly information collection.", tools: ["C#", ".NET", "Razor Pages", "Entity Framework Core", "SQL Server", "Power BI", "Git", "UI/UX design"], visual: "water" },
    { title: "Shift Guard", category: "Predictive Analytics | Classification | Safety", status: "Current Project", summary: "An exploration of whether historical work patterns, shift timing and recovery information can help identify shifts with a higher risk of becoming extended.", problem: "Existing monitoring is reactive. This research asks whether governed historical data can support earlier review.", contribution: ["Prepare and validate historical shift data", "Engineer features from work and recovery patterns", "Train and compare classification models", "Evaluate precision, recall and related measures", "Review signals with stakeholders", "Assess additional data only where privacy and governance allow"], approach: "Build a careful experimental pipeline, compare models transparently and keep human review central to any future use.", outcome: "Ongoing research. The predictive model is not deployed.", tools: ["Python", "pandas", "NumPy", "SQL Server", "Classification", "Feature engineering", "Model evaluation", "Power BI"], visual: "model" }
  ],
  moreWork: [
    { title: "Dispatch Performance", text: "Defined queue, delay, reassignment and unexpected-arrival measures for crew-level comparison using SQL and Power BI." },
    { title: "Succession and Talent Analytics", text: "Prepared measures for successor coverage, readiness and internal movement to support an executive workforce view." },
    { title: "Monthly Data Preparation", text: "Automated the extraction and restructuring of a recurring operational workbook using Python and pandas, creating a repeatable analytical dataset." }
  ],
  experience: [
    { period: "July 2025 to Present", role: "Graduate Development Programme, Data Science", company: "First Quantum Minerals, Trident Operations", description: "Work with managers and system owners across Safety, Mining, Process, Human Resources and Training to turn reporting needs into agreed measures, data checks and usable solutions.", points: ["Prepare and join operational and business information using SQL and Python", "Build and maintain ETL pipelines", "Investigate duplicates, missing fields and inconsistent definitions", "Develop Power BI reports with role-based access where required", "Automate alerts and recurring preparation", "Present findings, test with users and revise solutions as processes change"] },
    { period: "2022 to 2025", role: "Platform Developer", company: "Decarbonify AS", description: "Developed and maintained features for an ESG platform using Django, React, Next.js, PostgreSQL and REST APIs.", points: ["Developed frontend and backend features", "Designed database changes and integrated services", "Tested fixes and product improvements", "Translated product requirements into usable features", "Worked in Agile delivery cycles"] },
    { period: "2021 to 2022", role: "Software Developer Intern", company: "Decarbonify AS", description: "Gained practical experience across UI/UX design, frontend development, backend development and databases.", points: ["Moved from user research, wireframes and prototypes into developer handover", "Built responsive React and Next.js interfaces", "Worked on Django features, REST APIs, PostgreSQL tables and queries"] }
  ],
  research: [
    { label: "Published conference paper", title: "Can AI and IoT-Integrated Mobile Health Apps Effectively Improve Cognitive Health and Caregiver Support for Dementia?", meta: "Jessica Kaluiji, Shivani Chauhan, Arvind K. Sharma and Savita Wadhawan · Cognitive Neuroscience and Artificial Intelligence · Springer, 2026 · Pages 35 to 52", text: "Explored how artificial intelligence, connected devices and mobile health applications could support cognitive health and improve assistance for people living with dementia and their caregivers.", link: "https://doi.org/10.1007/978-3-032-19966-9_4", linkLabel: "View publication" },
    { label: "Master’s thesis", title: "Design and Development of an AI Adaptive User Interface for Dementia Care", meta: "Artificial intelligence · Human-computer interaction · Accessibility · Voice interaction · Adaptive interface design · Caregiver support", text: "Proposed and partially developed an adaptive interface using voice interaction, wake-word detection and machine-learning-based command classification. It is a research prototype, not a deployed healthcare product.", link: "https://github.com/kaluijijessica/AI-Powered-Adaptive-UI", linkLabel: "View repository" },
    { label: "Unpublished Research Paper", title: "Cross-Domain Performance Evaluation of AI-Language Models", meta: "T5 · MBart · MarianMT · BLEU · ROUGE · METEOR", text: "Compared T5, MBart and MarianMT across domains and translation tasks using established language-model evaluation metrics." }
  ],
  skills: [
    { group: "Analysis and modelling", items: ["Python", "pandas", "NumPy", "Exploratory data analysis", "Classification", "Feature engineering", "Model evaluation"] },
    { group: "Data engineering and reporting", items: ["SQL Server", "T-SQL", "ETL pipelines", "Data integration", "Data validation", "Data modelling", "Power BI", "DAX", "Power Query", "Excel"] },
    { group: "Development and automation", items: ["C#", ".NET", "Entity Framework Core", "Django", "React", "Next.js", "REST APIs", "PostgreSQL", "Power Automate", "Git"] },
    { group: "Product and design", items: ["Stakeholder interviews", "Requirements gathering", "User research", "Wireframing", "Prototyping", "UI/UX design", "Developer handover", "Agile delivery"] }
  ],
  education: [
    { period: "2023 to 2025", qualification: "Master of Computer Applications, Artificial Intelligence", institution: "Shoolini University", detail: "GPA: 8.82" },
    { period: "2019 to 2022", qualification: "Bachelor of Computer Applications", institution: "Marwadi University", detail: "GPA: 7.86" }
  ],
  noteTopics: ["Lessons from cross-functional rotations", "Building solutions with stakeholders", "Responsible use of AI", "The human side of data", "Designing tools people actually use", "Purpose, faith and professional growth"]
};
